name: Release Helm Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          branch: main
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.BACKPORT_TOKEN || github.token }}
